name = "Mathematics in Lean game"
version = "1.3.3"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Calculations world"
id = 1
levels = [
	"src/game/world1/level1.lean",
	"src/game/world1/level2.lean",
	"src/game/world1/level3.lean",
	"src/game/world1/level4.lean",
	"src/game/world1/level5.lean",
	"src/game/world1/level6.lean",
	"src/game/world1/level7.lean",
	"src/game/world1/level8.lean",
	"src/game/world1/level9.lean",
	"src/game/world1/level10.lean",
	"src/game/world1/level11.lean",
	"src/game/world1/level12.lean",
	"src/game/world1/level13.lean",
	"src/game/world1/level14.lean",
	"src/game/world1/level15.lean",
	"src/game/world1/level16.lean",
]

[[worlds]]
name = "Algebraic Structures world"
id = 2
parents = [1]
levels = [
	"src/game/world2/level1.lean",
	"src/game/world2/level2.lean",
	"src/game/world2/level3.lean",
	"src/game/world2/level4.lean",
	"src/game/world2/level5.lean",
	"src/game/world2/level6.lean",
]

[[worlds]]
name = "Theorems and Lemmas world"
id = 3
parents = [2]
levels = [
	"src/game/world3/level1.lean",
	"src/game/world3/level2.lean",
	"src/game/world3/level3.lean",
	"src/game/world3/level4.lean",
	"src/game/world3/level5.lean",
	"src/game/world3/level6.lean",
	"src/game/world3/level7.lean",
	"src/game/world3/level8.lean",
	"src/game/world3/level9.lean",
]

[[worlds]]
name = "Order and Divisibility world"
id = 4
parents = [3]
levels = [
	"src/game/world4/level1.lean",
	"src/game/world4/level2.lean",
	"src/game/world4/level3.lean",
	"src/game/world4/level4.lean",
	"src/game/world4/level5.lean",
	"src/game/world4/level6.lean",
	"src/game/world4/level7.lean",
	"src/game/world4/level8.lean",
]

[[worlds]]
name = "Advanced Algebraic Structures world"
id = 5
parents = [2]
levels = [
	"src/game/world5/level1.lean",
	"src/game/world5/level2.lean",
	"src/game/world5/level3.lean",
	"src/game/world5/level4.lean",
	"src/game/world5/level5.lean",
	"src/game/world5/level6.lean",
	"src/game/world5/level7.lean",
	"src/game/world5/level8.lean",
	"src/game/world5/level9.lean",
]
